{
 "title": "Job Statistics",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "window", "label": "window", "query": "5m,10m,30m,1h,6h,12h,24h" },
   {
    "name": "pipeline",
    "label": "pipeline",
    "query": "label_values(job_latency_seconds_count, pipeline_id)"
   }
  ]
 },
 "panels": [
  {
   "title": "Aggregate Request Status, pipeline=$pipeline [Rate]",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(job_latency_seconds_count{pipeline_id=~\"$pipeline\"}[$window])) by (status)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Failures, pipeline=$pipeline [Rate]",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(job_latency_seconds_count{pipeline_id=~\"$pipeline\",status=\"failure\"}[$window])) by (pipeline_id)",
     "legendFormat": "{{pipeline_id}}"
    }
   ]
  },
  {
   "title": "Median Latencies by Pipeline",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(.50, sum(rate(job_latency_seconds_bucket{stage_id=\"total\",pipeline_id=~\"$pipeline\"}[$window])) by (pipeline_id, le))",
     "legendFormat": "{{pipeline_id}}"
    }
   ]
  },
  {
   "title": "95th Quantile Latencies by Pipeline",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(.95, sum(rate(job_latency_seconds_bucket{stage_id=\"total\",pipeline_id=~\"$pipeline\"}[$window])) by (pipeline_id, le))",
     "legendFormat": "{{pipeline_id}}"
    }
   ]
  },
  {
   "title": "Pipeline Latency Dist., pipeline=$pipeline",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(1.0, sum(rate(job_latency_seconds_bucket{pipeline_id=~\"$pipeline\",stage_id=\"total\"}[$window])) by (le))",
     "legendFormat": "1.0qt"
    },
    {
     "expr": "histogram_quantile(.5, sum(rate(job_latency_seconds_bucket{pipeline_id=~\"$pipeline\",stage_id=\"total\"}[$window])) by (le))",
     "legendFormat": "0.5qt"
    },
    {
     "expr": "histogram_quantile(0.01, sum(rate(job_latency_seconds_bucket{pipeline_id=~\"$pipeline\",stage_id=\"total\"}[$window])) by (le))",
     "legendFormat": "0.01qt"
    }
   ]
  },
  {
   "title": "50th Qt. Latencies by Stage, pipeline=$pipeline",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(.5, sum(rate(job_latency_seconds_bucket{pipeline_id=~\"$pipeline\",stage_id!=\"total\"}[$window])) by (stage_id,le))",
     "legendFormat": "stage={{stage_id}}-50qt"
    }
   ]
  },
  {
   "title": "Worker 95th Quantile Latencies, pipeline=$pipeline",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(.95, sum(rate(job_latency_seconds_bucket{pipeline_id=~\"$pipeline\",stage_id=\"total\"}[$window])) by (worker_id,le))",
     "legendFormat": "{{worker_id}}-95qt"
    }
   ]
  }
 ]
}